make_dataset:
  test_split: 0.2
  seed: 2023

models:
  RandomForestClassifier:
    n_estimators: 100
    max_depth: 5
    random_state: 42
  
  XGBClassifier:
    n_estimators: 100 # Number of boosting rounds
    learning_rate: 0.1 # Learning rate
    max_depth: 5 # Maximum depth of each tree
    random_state: 42

  DecisionTreeClassifier:
    criterion: "gini" # Impurity measure
    max_depth: 5 # Maximum depth of the tree
    min_samples_split: 2 # Minimum samples required for split
    min_samples_leaf: 1 # Minimum samples required at a leaf node
    random_state: 42 # Seed for random number generator  

  ExtraTreesClassifier:
    n_estimators: 100
    max_depth: 5
    min_samples_split: 2  
    random_state : 42

  GradientBoostingClassifier :
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3
    random_state : 42
