name: CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3 
    - uses: actions/setup-python@v4
    - uses: iterative/setup-cml@v2   

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Pull DVC-Tracked Data
      run: |
        dvc pull  # Pulls the tracked data    

    - name: Run main file
      run: |
        dvc repro     

    # - name: Create CML report
    # env:
    #   REPO_TOKEN: ${{ secrets.Harsh_Chitaliya }
    # run: |

    #   echo "#first line of our report" >> report.md
    #   echo "## model" >> report.md
    #   echo '![](./models/model.joblib "model" )' >> report.md
    #   echo "## model params" >> report.md
    #   echo '![](./models/best_params.yaml "params")' >> report.md

    #   cml comment create report.md




        
